# Generated by Django 4.2.7 on 2024-02-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('messageId', models.AutoField(primary_key=True, serialize=False)),
                ('messageDate', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plantId', models.AutoField(primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=255)),
                ('plantDescription', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('plantAddress', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=255)),
                ('userAddress', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('lives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arosajeapi.city')),
            ],
        ),
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='plant_images/')),
                ('imageDate', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arosajeapi.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='keepers',
            field=models.ManyToManyField(related_name='plants_kept', to='arosajeapi.user'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_receive_messages', models.ManyToManyField(related_name='owner_messages', to='arosajeapi.messagehistory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arosajeapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kept_plants', models.ManyToManyField(related_name='guardian_kept_plants', to='arosajeapi.plant')),
                ('send_receive_messages', models.ManyToManyField(related_name='guardian_messages', to='arosajeapi.messagehistory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arosajeapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Botanist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provide_tips', models.ManyToManyField(related_name='botanist_tips', to='arosajeapi.plant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='arosajeapi.user')),
            ],
        ),
    ]
