# Generated by Django 4.2.7 on 2024-04-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arosajeapi', '0002_customuser_plant_owner_alter_botanist_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userAddress',
        ),
    ]
